#apollo相关
#app:
#  id: its-shop-member_id
#apollo:
#  meta: http://192.168.118.128:8080
#  bootstrap:
#    enabled: true
#    namespaces: application
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.its.member.domain.entity.**
server:
  port: 8200
spring:
  application:
    name: its-shop-member
  zipkin:
    base-url: localhost:8004
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    min-evictable-idle-time-millis: 1800000
    password: 123456
    test-on-borrow: true
    test-while-idle: true
    time-between-eviction-runs-millis: 300000
    url: jdbc:mysql://localhost:3306/it_student?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    validation-query: SELECT 1 FROM DUAL
  redis:
    database: 1
    host: 192.168.50.126
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    port: 6379
#---------------------OAuth2---------------------
#security:
#  oauth2:
#    client:
#      access-token-uri: http://localhost:8003/oauth/token
#      user-authorization-uri: http://localhost:8003/oauth/authorize
#      #client-id: web
#    resource:
#      user-info-uri:  http://localhost:80/auth/api/member
#      prefer-token-info: false
      
#----------------------超时配置-------------------
#ribbon:
#  ReadTimeout: 3000
#  ConnectTimeout: 3000
#  MaxAutoRetries: 1
#  MaxAutoRetriesNextServer: 2
#  eureka:
#    enabled: true
#hystrix:
#  command:
#    default:
#      execution:
#        timeout:
#          enabled: true
#        isolation:
#          thread:
#            timeoutInMilliseconds: 3500
