#app:
  #id: its-shop-zuul_id
#apollo:
  #meta: http://192.168.118.128:8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
server:
  port: 80
spring:
  application:
    name: its-shop-zuul
zuul:
  routes:
    weixin:
      path: /weixin/**
      serviceId: its-shop-weixin
    member:
      path: /member/**
      serviceId: its-shop-member
    auth:
      paht: /auth/**
      serviceId: its-shop-auth

#---------------------OAuth2---------------------
#security:
#  oauth2:
#    client:
#      access-token-uri: http://localhost:80/auth/oauth/token
#      user-authorization-uri: http://localhost:80/auth/oauth/authorize
#      #client-id: web
#    resource:
#      user-info-uri:  http://localhost:80/auth/api/member
#      prefer-token-info: false